package com.tapi.android.example.util

object Constance {
const val ACTION_CLICK_PHOTO="ACTION_CLICK_PHOTO"
const val ACTION_CLICK_BACK_DETAIL_TO_HOME="ACTION_CLICK_BACK_DETAIL_TO_HOME"
const val ACTION_CLICK_BACK_PRESS="ACTION_CLICK_BACK_PRESS"
}